# Generated by Django 4.1.7 on 2023-04-25 22:12

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_phone_number_user_phone_number2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='user name', max_length=150, validators=[common.validators.validate_name], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='user last name', max_length=150, validators=[common.validators.validate_name], verbose_name='last name'),
        ),
    ]
