# Generated by Django 4.1.7 on 2023-04-25 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_remove_partner_address_and_more'),
        ('projects', '0003_project_owner_project_summary_alter_project_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='price',
        ),
        migrations.AlterField(
            model_name='project',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='partners.partner'),
        ),
    ]
