# Generated by Django 4.1.7 on 2023-04-25 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_price_alter_project_partner'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_task', to='projects.project'),
            preserve_default=False,
        ),
    ]
