# Generated by Django 4.1.7 on 2023-04-25 22:12

import common.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partner_code_alter_partnercontactperson_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='address',
        ),
        migrations.RemoveField(
            model_name='partnercontactperson',
            name='email',
        ),
        migrations.RemoveField(
            model_name='partnercontactperson',
            name='name',
        ),
        migrations.AddField(
            model_name='partnercontactperson',
            name='first_name',
            field=models.CharField(default='user name', max_length=150, validators=[common.validators.validate_name], verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='partnercontactperson',
            name='last_name',
            field=models.CharField(default='user last name', max_length=150, validators=[common.validators.validate_name], verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='code',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partnercontactperson',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_person', to='partners.partner'),
        ),
        migrations.AlterField(
            model_name='partnercontactperson',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
